server:
  port: 7771

spring:
  application:
    name: SystemProvider
  #ActiveMQ配置
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
  jms:
    #false：queue模式  true:topic模式
    pub-sub-domain: false
  #Redis配置
  redis:
    host: localhost
    port: 6379

dubbo:
  #Dubbo信息
  application:
    name: system-provider
  #协议信息
  #protocol:
  #   name: dubbo
  #    port: 20880
  #注册中心信息
  registry:
    #N/A
    address: zookeeper://127.0.0.1:2181
    #protocol: dubbo
  #扫描注解包
  scan:
    base-packages: com.systemprovider.service.impl

topicName: topic
queueName: queue
firstQueue: FirstQueue
secondQueue: SecondQueue